font_family family="JetBrains Mono"
background_opacity 0.8
background #191724
foreground #e0def4

#Tab bar
tab_bar_edge top
# TODO implement custom function
tab_bar_style powerline
tab_title_max_length 2

