wallpaper {
    monitor = DP-2
    path = files/repos/dotfiles/wallpapers/the-legend-of-zelda-tears-of-the-kingdom-ei.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = files/repos/dotfiles/wallpapers/zelda_link.jpg
    fit_mode = cover
}

splash = false

