wallpaper {
    monitor = DP-2
    path = wallpapers/the-legend-of-zelda-tears-of-the-kingdom-ei.jpg
    fit_mode = cover
}

wallpaper {
    monitor = DP-3
    path = wallpapers/zelda_link.jpg
    fit_mode = cover
}


